//$file${.::soundGenHSM.cc} ##################################################
//
// Model: synthControl.qm
// File:  ${.::soundGenHSM.cc}
//
// This code has been generated by QM 4.3.0 (https://www.state-machine.com/qm).
// DO NOT EDIT THIS FILE MANUALLY. All your changes will be lost.
//
// This program is open source software: you can redistribute it and/or
// modify it under the terms of the GNU General Public License as published
// by the Free Software Foundation.
//
// This program is distributed in the hope that it will be useful, but
// WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY
// or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License
// for more details.
//
//$endhead${.::soundGenHSM.cc} ###############################################

#include "soundGenHSM.h"

using namespace QP;
using namespace MAINBSP;

//synth_params_t synth_params;

Q_DEFINE_THIS_FILE

//*============== ask QM to declare the Blinky class ================*/
//$declare${AOs::SoundGenHSM} ################################################
//${AOs::SoundGenHSM} ........................................................
class SoundGenHSM : public QP::QActive {
private:
    QP::QTimeEvt m_timeEvt;

public:
    SoundGenHSM();

protected:
    static QP::QState initial(SoundGenHSM * const me, QP::QEvt const * const e);
    static QP::QState off(SoundGenHSM * const me, QP::QEvt const * const e);
    static QP::QState on(SoundGenHSM * const me, QP::QEvt const * const e);
};
//$enddecl${AOs::SoundGenHSM} ################################################

// local objects --------------------------------------------------------------
SoundGenHSM l_soundGenHSM;

// global objects ------------------------------------------------------------
QActive * const AO_SoundGenHSM = &l_soundGenHSM; // opaque pointer

/*================ ask QM to define the Blinky class ================*/
// Check for the minimum required QP version
#if (QP_VERSION < 630U) || (QP_VERSION != ((QP_RELEASE^4294967295U) % 0x3E8U))
#error qpcpp version 6.3.0 or higher required
#endif

//$define${AOs::SoundGenHSM} #################################################
//${AOs::SoundGenHSM} ........................................................
//${AOs::SoundGenHSM::SoundGenHSM} ...........................................
SoundGenHSM::SoundGenHSM()
  : QActive(Q_STATE_CAST(&SoundGenHSM::initial)),
    m_timeEvt(this, TIMEOUT_SIG, 0U)
{}

//${AOs::SoundGenHSM::SM} ....................................................
QP::QState SoundGenHSM::initial(SoundGenHSM * const me, QP::QEvt const * const e) {
    //${AOs::SoundGenHSM::SM::initial}
    me->m_timeEvt.armX(BSP::TICKS_PER_SEC/2, BSP::TICKS_PER_SEC/2);

    QS_FUN_DICTIONARY(&off);
    QS_FUN_DICTIONARY(&on);

    return Q_TRAN(&off);
}
//${AOs::SoundGenHSM::SM::off} ...............................................
QP::QState SoundGenHSM::off(SoundGenHSM * const me, QP::QEvt const * const e) {
    QP::QState status_;
    switch (e->sig) {
        //${AOs::SoundGenHSM::SM::off}
        case Q_ENTRY_SIG: {
            BSP::ledOff();
            status_ = Q_HANDLED();
            break;
        }
        //${AOs::SoundGenHSM::SM::off::TIMEOUT}
        case TIMEOUT_SIG: {
            status_ = Q_TRAN(&on);
            break;
        }
        default: {
            status_ = Q_SUPER(&top);
            break;
        }
    }
    return status_;
}
//${AOs::SoundGenHSM::SM::on} ................................................
QP::QState SoundGenHSM::on(SoundGenHSM * const me, QP::QEvt const * const e) {
    QP::QState status_;
    switch (e->sig) {
        //${AOs::SoundGenHSM::SM::on}
        case Q_ENTRY_SIG: {
            BSP::ledOn();
            //synth_params_t synth_params;
            //fillBuffer(&synth_params);
            status_ = Q_HANDLED();
            break;
        }
        //${AOs::SoundGenHSM::SM::on::TIMEOUT}
        case TIMEOUT_SIG: {
            status_ = Q_TRAN(&off);
            break;
        }
        default: {
            status_ = Q_SUPER(&top);
            break;
        }
    }
    return status_;
}
//$enddef${AOs::SoundGenHSM} #################################################


